= IKT Systemarchitektur
:toc-title: Inhaltsverzeichnis
:toc: left
:numbered:
:imagesdir: ..
:imagesdir: ./img
:imagesoutdir: ./img




== Einführung und Ziele




=== Qualitätsziele






=== Aufgabenstellung







== Randbedingungen






== Kontextabgrenzung



In diesem Kapitel wird der Kontext betrachteten Systems (IKT) aufgeführt. 

Die nachfolgende Tabelle beschreibt die Nachbarsysteme an das betrachtete System.

[cols="5,10a" options="header"]
|====
|Name | Beschreibung
|====
=== Fachlicher Kontext


[plantuml, png]
....
skinparam monochrome true
skinparam componentStyle uml2
component "IKT" #grey

...

In diesem Kapitel werden die Aktoren (Actor) und Nachbarsysteme (Neighboring) des betrachteten Systems (IKT) aufgeführt. 

Die nachfolgende Tabelle beschreibt die Aktoren an das betrachtete System.

[cols="5,10a" options="header"]
|====
|Name | Beschreibung

Die nachfolgende Tabelle beschreibt die Kommunikationsflüsse (Flows) zwischen allen Teilnehmern.

[cols="5,5,5,5,10a" options="header"]
|====
|Von | Zu | Interaktion | Richtung | Beschreibung
|====


=== Technischer Kontext


[plantuml, png]
....
skinparam monochrome true
skinparam componentStyle uml2
component "IKT" #grey

...

In diesem Kapitel werden die Schnittstellen an die Nachbarsysteme (Neighboring) des betrachteten Systems (IKT) aufgeführt. 

Die nachfolgende Tabelle beschreibt die Schnittstellen an das betrachtete System.

[cols="5,10a" options="header"]
|====
|Name | Beschreibung

Die nachfolgende Tabelle beschreibt die Kommunikationsflüsse (Flows) zwischen allen Teilnehmern.

[cols="5,5,5,5,10a" options="header"]
|====
|Von | Zu | Interaktion | Richtung | Beschreibung
|====



== Bausteinsicht




=== Ebene 1: IKT <System> (Whitebox)





 
=== Ebene 2: Plattform <SystemLayer> (Whitebox)






=== Ebene 3: Windows 2016 <SystemComponent> (Whitebox)






=== Ebene 4: Windows Server Standard Virtual <SystemConfiguration> (Whitebox)






=== Ebene 4: Windows Server 2016 BareMetal <SystemConfiguration> (Whitebox)







== Verteilsicht




=== Bauen






=== Paketierung






=== Verteilung




==== QA






==== Produktion







=== Test






=== Überwachung







== Konzepte






== Entwurfsentscheidungen






== Qualitätsszenarios






== Risiken und technische Schulden






== Produktesicht






== Anforderungsabdeckung




=== SU01_Funktionalität








