@startuml
skinparam monochrome true
skinparam componentStyle uml2
actor Role1 as "Role1"
actor Role2 as "Role2"

' Begin Protected Region [[layouting]]

' End Protected Region   [[layouting]]

@enduml
' Actifsource ID=[dc5bfacd-eaac-11e8-88d3-bfc6b992bdec,63ededea-ff94-11e8-9d0c-c96c1e9b7b46,Hash]
