@startuml
skinparam monochrome true
component "Chess" #grey
component "FTP"
component "Table"
(FTP) --> (Chess) : ssss

@enduml
' Actifsource ID=[dc5bfacd-eaac-11e8-88d3-bfc6b992bdec,35964cc6-fa45-11e8-af47-e5bdd8100025,Hash]
