= Sprint 3
:numbered:
:imagesdir: ..
:imagesdir: ./img
:imagesoutdir: ./img




== Sprint 3 Ziele



[cols="2,10a" options="header"]
|===
|Name|Beschreibung
|===


== Sprint 3 Kapazität



.Zusammenfassung
[cols="10,20"]
|===
|*Butto Kapazität [h]*|144
|*Netto Kapazität [h]*|100
|*Aufwand [SP]*|0.0
|*Druck (Aufwand/Netto Kapazität)*|0.0
|===

[cols="10,10,10,10" options="header"]
|===
|Person|Brutto Kapazität [h]|Produktivität|Netto Kapazität [h]
|Pascal Meier
|144
|70%
|100
|===

.Kapazität 
[cols="4,^4" options="header"]
|===
|Date
|Pascal Meier
|
{set:cellbgcolor:none}
2016-05-27_Fri
^|
{set:cellbgcolor:#009933}
8
|
{set:cellbgcolor:none}
2016-05-28_Sat
^|
{set:cellbgcolor:#d3d3d3}
0
|
{set:cellbgcolor:none}
2016-05-29_Sun
^|
{set:cellbgcolor:#d3d3d3}
0
|
{set:cellbgcolor:none}
2016-05-30_Mon
^|
{set:cellbgcolor:#009933}
8
|
{set:cellbgcolor:none}
2016-05-31_Tue
^|
{set:cellbgcolor:#009933}
8
|
{set:cellbgcolor:none}
2016-06-01_Wed
^|
{set:cellbgcolor:#009933}
8
|
{set:cellbgcolor:none}
2016-06-02_Thu
^|
{set:cellbgcolor:#009933}
8
|
{set:cellbgcolor:none}
2016-06-03_Fri
^|
{set:cellbgcolor:#009933}
8
|
{set:cellbgcolor:none}
2016-06-04_Sat
^|
{set:cellbgcolor:#d3d3d3}
0
|
{set:cellbgcolor:none}
2016-06-05_Sun
^|
{set:cellbgcolor:#d3d3d3}
0
|
{set:cellbgcolor:none}
2016-06-06_Mon
^|
{set:cellbgcolor:#009933}
8
|
{set:cellbgcolor:none}
2016-06-07_Tue
^|
{set:cellbgcolor:#009933}
8
|
{set:cellbgcolor:none}
2016-06-08_Wed
^|
{set:cellbgcolor:#009933}
8
|
{set:cellbgcolor:none}
2016-06-09_Thu
^|
{set:cellbgcolor:#009933}
8
|
{set:cellbgcolor:none}
2016-06-10_Fri
^|
{set:cellbgcolor:#009933}
8
|
{set:cellbgcolor:none}
2016-06-11_Sat
^|
{set:cellbgcolor:#d3d3d3}
0
|
{set:cellbgcolor:none}
2016-06-12_Sun
^|
{set:cellbgcolor:#d3d3d3}
0
|
{set:cellbgcolor:none}
2016-06-13_Mon
^|
{set:cellbgcolor:#009933}
8
|
{set:cellbgcolor:none}
2016-06-14_Tue
^|
{set:cellbgcolor:#009933}
8
|
{set:cellbgcolor:none}
2016-06-15_Wed
^|
{set:cellbgcolor:#009933}
8
|
{set:cellbgcolor:none}
2016-06-16_Thu
^|
{set:cellbgcolor:#009933}
8
|
{set:cellbgcolor:none}
2016-06-17_Fri
^|
{set:cellbgcolor:#009933}
8
|
{set:cellbgcolor:none}
2016-06-18_Sat
^|
{set:cellbgcolor:#d3d3d3}
0
|
{set:cellbgcolor:none}
2016-06-19_Sun
^|
{set:cellbgcolor:#d3d3d3}
0
|
{set:cellbgcolor:none}
2016-06-20_Mon
^|
{set:cellbgcolor:#009933}
8
|
{set:cellbgcolor:none}
2016-06-21_Tue
^|
{set:cellbgcolor:#009933}
8

|===
{set:cellbgcolor:none}


== Sprint 3 SprintBacklog 



[cols="10,20a,^5,^5,5,^5" options="header"]
|===
|Name|Beschreibung|State|Verantwortlich(e)|Lieferergbnis|Aufwand [SP]
|===



