@startuml
skinparam monochrome true
skinparam componentStyle uml2



show stereotype

rectangle __X_FA__F___N_RSA__O_ as "2FA (RSA)" <<$token_service>> {
}

rectangle Virtual__F_Machine__F___N_VM__O_ as "Virtual Machine (VM)" <<$virtual_server>> {
}
__X_FA__F___N_RSA__O_ -down-> Virtual__F_Machine__F___N_VM__O_ : verwendet 

' Begin Protected Region [[layouting]]

' End Protected Region   [[layouting]]

@enduml
' Actifsource ID=[dc5bfacd-eaac-11e8-88d3-bfc6b992bdec,1dbdfef9-0e1a-11e9-8b4c-f9aec93d8b56,Hash]
