@startuml
skinparam monochrome true
skinparam componentStyle uml2



show stereotype

rectangle Datenablage as "Datenablage" <<SystemComponent>> {
	rectangle Distributed__F_File__F_System__F___N_DFS__O_ as "Distributed File System (DFS)" <<$file_server>> {
	}		

}

' Begin Protected Region [[layouting]]

' End Protected Region   [[layouting]]

@enduml
' Actifsource ID=[dc5bfacd-eaac-11e8-88d3-bfc6b992bdec,62ed29f1-0a97-11e9-a2c0-1d5f7e333c03,Hash]
