@startuml
skinparam monochrome true
skinparam componentStyle uml2



show stereotype

rectangle Endpoint__F_Protection as "Endpoint Protection" <<SystemComponent>> {
	rectangle Endpoint__F_Protection__F_Orchestrator__F___N_EPO__O_ as "Endpoint Protection Orchestrator (EPO)" <<$lock_with_key_security>> {
	}		

}

' Begin Protected Region [[layouting]]

' End Protected Region   [[layouting]]

@enduml
' Actifsource ID=[dc5bfacd-eaac-11e8-88d3-bfc6b992bdec,6eb02e43-0a97-11e9-a2c0-1d5f7e333c03,Hash]
