@startuml


skinparam monochrome true
skinparam componentStyle uml2



show stereotype

rectangle Application__F_Server__F___N_APP__O_ as "Application Server (APP)" <<$web_server>> {
}

rectangle Windows__F___N_WIN__O_ as "Windows (WIN)" <<$windows_server>> {
}
Application__F_Server__F___N_APP__O_ -down-> Windows__F___N_WIN__O_ : verwendet 

' Begin Protected Region [[layouting]]

' End Protected Region   [[layouting]]

@enduml
' Actifsource ID=[dc5bfacd-eaac-11e8-88d3-bfc6b992bdec,f907a698-0e19-11e9-8b4c-f9aec93d8b56,Hash]
