@startuml


skinparam monochrome true
skinparam componentStyle uml2



show stereotype

rectangle Jump__F_Host as "Jump Host" <<SystemComponent>> {
}

rectangle Operating__F_System as "Operating System" <<SystemComponent>> {
}
Jump__F_Host -down-> Operating__F_System : verwendet 

' Begin Protected Region [[layouting]]

' End Protected Region   [[layouting]]

@enduml
' Actifsource ID=[dc5bfacd-eaac-11e8-88d3-bfc6b992bdec,2236dd0a-0e1a-11e9-8b4c-f9aec93d8b56,Hash]
