@startuml


skinparam monochrome true
skinparam componentStyle uml2



show stereotype

rectangle Redhat__F_Virtual__F___N_RHT__S_VM__O_ as "Redhat Virtual (RHT-VM)" <<$linux>> {
}

rectangle Virtual__F_Machine__F___N_VM__O_ as "Virtual Machine (VM)" <<$virtual_server>> {
}
rectangle Configuration__F_Management__F___N_CMG__O_ as "Configuration Management (CMG)" <<$central_management_service>> {
}
rectangle Redhat__F_Satellite__F___N_RHS__O_ as "Redhat Satellite (RHS)" <<$install>> {
}
Redhat__F_Virtual__F___N_RHT__S_VM__O_ -down-> Virtual__F_Machine__F___N_VM__O_ : verwendet 
Configuration__F_Management__F___N_CMG__O_ -up-> Redhat__F_Virtual__F___N_RHT__S_VM__O_ : verwendet
Redhat__F_Satellite__F___N_RHS__O_ -up-> Redhat__F_Virtual__F___N_RHT__S_VM__O_ : verwendet

' Begin Protected Region [[layouting]]

' End Protected Region   [[layouting]]

@enduml
' Actifsource ID=[dc5bfacd-eaac-11e8-88d3-bfc6b992bdec,ed0d8c62-0e19-11e9-8b4c-f9aec93d8b56,Hash]
