@startuml


skinparam monochrome true
skinparam componentStyle uml2



show stereotype

rectangle Storage as "Storage" <<SystemComponent>> {
	rectangle Block__F_Storage__F_Service__F___N_BSS__O_ as "Block Storage Service (BSS)" <<$database>> {
	}		

}

' Begin Protected Region [[layouting]]

' End Protected Region   [[layouting]]

@enduml
' Actifsource ID=[dc5bfacd-eaac-11e8-88d3-bfc6b992bdec,27bbc542-0a96-11e9-9f72-e5610a9d4cd3,Hash]
