@startuml
skinparam monochrome true
skinparam componentStyle uml2



show stereotype

rectangle Plattform as "Plattform" <<SystemLayer>> {
	rectangle Application as "Application" <<SystemComponent>> {
	}		
	rectangle Datenablage as "Datenablage" <<SystemComponent>> {
	}		

}

' Begin Protected Region [[layouting]]

' End Protected Region   [[layouting]]

@enduml
' Actifsource ID=[dc5bfacd-eaac-11e8-88d3-bfc6b992bdec,89556316-0a95-11e9-9f72-e5610a9d4cd3,Hash]
