@startuml


skinparam monochrome true
skinparam componentStyle uml2



show stereotype

rectangle ESX__F_Physical__F___N_VMH__O_ as "ESX Physical (VMH)" <<$virtual_application_server>> {
}

rectangle Kontron__F_Server__F___N_KON__O_ as "Kontron Server (KON)" <<$server_generic_green>> {
}
rectangle HPE__F_Server__F___N_HPE__O_ as "HPE Server (HPE)" <<$server_generic_blue>> {
}
rectangle Virtual__F_Machine__F___N_VM__O_ as "Virtual Machine (VM)" <<$virtual_server>> {
}
ESX__F_Physical__F___N_VMH__O_ -down-> Kontron__F_Server__F___N_KON__O_ : verwendet 
ESX__F_Physical__F___N_VMH__O_ -down-> HPE__F_Server__F___N_HPE__O_ : verwendet 
Virtual__F_Machine__F___N_VM__O_ -up-> ESX__F_Physical__F___N_VMH__O_ : verwendet

' Begin Protected Region [[layouting]]

' End Protected Region   [[layouting]]

@enduml
' Actifsource ID=[dc5bfacd-eaac-11e8-88d3-bfc6b992bdec,eee113f4-0e19-11e9-8b4c-f9aec93d8b56,Hash]
