@startuml


skinparam monochrome true
skinparam componentStyle uml2



show stereotype

rectangle Management as "Management" <<SystemLayer>> {
	rectangle Hypervisor__F_Management as "Hypervisor Management" <<SystemComponent>> {
	}		
	rectangle Backup__F_Management as "Backup Management" <<SystemComponent>> {
	}		
	rectangle Jump__F_Host as "Jump Host" <<SystemComponent>> {
	}		
	rectangle Deployment as "Deployment" <<SystemComponent>> {
	}		
	rectangle Monitoring as "Monitoring" <<SystemComponent>> {
	}		

}

' Begin Protected Region [[layouting]]

' End Protected Region   [[layouting]]

@enduml
' Actifsource ID=[dc5bfacd-eaac-11e8-88d3-bfc6b992bdec,a4ab5f98-0a95-11e9-9f72-e5610a9d4cd3,Hash]
