@startuml


skinparam monochrome true
skinparam componentStyle uml2



show stereotype

rectangle __Z_c974acd__S_f16e__S_11e8__S_b3e7__S_15e2dd8d9b05 as "4c974acd-f16e-11e8-b3e7-15e2dd8d9b05" <<$windows_server>> {
}

rectangle Kontron__F_Server__F___N_KON__O_ as "Kontron Server (KON)" <<$server_generic_green>> {
}
rectangle Master__F_Active__F_Directory__F___N_MDC__O_ as "Master Active Directory (MDC)" <<$domain_controller>> {
}
__Z_c974acd__S_f16e__S_11e8__S_b3e7__S_15e2dd8d9b05 -down-> Kontron__F_Server__F___N_KON__O_ : verwendet 
Master__F_Active__F_Directory__F___N_MDC__O_ -up-> __Z_c974acd__S_f16e__S_11e8__S_b3e7__S_15e2dd8d9b05 : verwendet

' Begin Protected Region [[layouting]]

' End Protected Region   [[layouting]]

@enduml
' Actifsource ID=[dc5bfacd-eaac-11e8-88d3-bfc6b992bdec,10a862ac-0e1a-11e9-8b4c-f9aec93d8b56,Hash]
