@startuml


skinparam monochrome true
skinparam componentStyle uml2



show stereotype

rectangle Hypervisor__F_Management as "Hypervisor Management" <<SystemComponent>> {
}

rectangle Virtual__F_Compute as "Virtual Compute" <<SystemComponent>> {
}
Hypervisor__F_Management -down-> Virtual__F_Compute : verwendet 

' Begin Protected Region [[layouting]]

' End Protected Region   [[layouting]]

@enduml
' Actifsource ID=[dc5bfacd-eaac-11e8-88d3-bfc6b992bdec,3e73dda4-0e1a-11e9-8b4c-f9aec93d8b56,Hash]
