@startuml
skinparam monochrome true
skinparam componentStyle uml2



show stereotype

rectangle Identity__F_Access__F_Management as "Identity Access Management" <<SystemComponent>> {
}

rectangle Directory__F_Services as "Directory Services" <<SystemComponent>> {
}
Identity__F_Access__F_Management -down-> Directory__F_Services : verwendet 

' Begin Protected Region [[layouting]]

' End Protected Region   [[layouting]]

@enduml
' Actifsource ID=[dc5bfacd-eaac-11e8-88d3-bfc6b992bdec,047cff65-0e1a-11e9-8b4c-f9aec93d8b56,Hash]
