@startuml


skinparam monochrome true
skinparam componentStyle uml2

show stereotype

rectangle TN__F_IA2__F___N_982__O_ as "TN IA2 (982)" <<Teilnetz>> {
}


' Begin Protected Region [[layouting]]

' End Protected Region   [[layouting]]

@enduml
' Actifsource ID=[dc5bfacd-eaac-11e8-88d3-bfc6b992bdec,f02b245f-0eb1-11e9-9f19-6d15636f4ecc,Hash]
