@startuml
skinparam monochrome true
skinparam componentStyle uml2
!include <office/databases/database>
!include <office/servers/server_generic_green>
!include <office/servers/virtual_application_server>
!include <office/Servers/virtual_server>
!include <office/Servers/virtual_server>
!include <office/Servers/windows_server>
!include <office/databases/monitoring_store>
!include <office/Servers/virtual_server>
!include <office/Servers/virtual_server>
!include <office/Servers/virtual_server>
!include <office/Servers/windows_server>
!include <office/security/credentials>
!include <office/Servers/virtual_server>
!include <office/Servers/windows_server>
!include <office/services/central_management_service>
!include <office/servers/server_generic_green>
!include <office/servers/virtual_application_server>
!include <office/Servers/virtual_server>
!include <office/Servers/windows_server>
!include <office/servers/certificate_authority>
!include <office/Servers/virtual_server>
!include <office/Servers/windows_server>
!include <office/servers/web_server>
!include <office/Servers/virtual_server>
!include <office/Servers/windows_server>
!include <office/databases/monitoring_store>
!include <office/Servers/virtual_server>
!include <office/Servers/windows_server>
!include <office/services/central_management_service>
!include <office/Servers/virtual_server>
!include <office/Servers/server_farm>
!include <office/Servers/virtual_server>
!include <office/Servers/windows_server>
!include <office/concepts/backup_local>
!include <office/Servers/virtual_server>
!include <office/Servers/windows_server>
!include <office/servers/certificate_authority>
!include <office/Servers/virtual_server>
!include <office/Servers/windows_server>
!include <office/Security/lock_with_key_security>
!include <office/Servers/virtual_server>
!include <cloudinsight/linux>
!include <office/communications/central_management_service>
!include <office/Servers/virtual_server>
!include <office/Servers/windows_server>
!include <office/Servers/file_server>
!include <office/Servers/virtual_server>
!include <office/Servers/windows_server>
!include <office/services/central_management_service>
!include <office/servers/server_generic_green>
!include <office/servers/virtual_application_server>
!include <office/Servers/virtual_server>
!include <office/Servers/windows_server>
!include <office/servers/reverse_proxy>
!include <office/Servers/virtual_server>
!include <office/Servers/windows_server>
!include <office/concepts/backup_local>
!include <office/Servers/virtual_server>
!include <office/Servers/windows_server>
!include <office/concepts/install>
!include <office/Servers/virtual_server>
!include <cloudinsight/linux>
!include <office/concepts/install>
!include <office/servers/server_generic_green>
!include <office/Servers/windows_server>
!include <office/Servers/domain_controller>
!include <office/security/lock_with_key_security_blue>

show stereotype

rectangle NMS__F___S___F_Stao__F_A as "NMS - Stao A" <<Standort>> {
	rectangle BSS__S_NMS__S_BABS__S_00__F__aA_NMS__F___S___F_Stao__F_A_aC_ as "BSS-NMS-BABS-00 [NMS - Stao A]" <<$database>> {
	
	}
	rectangle VMH__S_NMS__S_BABS__S_00__F___N_KON__O_ as "VMH-NMS-BABS-00 (KON)" <<$server_generic_green>> {
		rectangle VMH__S_NMS__S_BABS__S_00__F__aA_NMS__F___S___F_Stao__F_A_aC_ as "VMH-NMS-BABS-00 [NMS - Stao A]" <<$virtual_application_server>> {
		
		}
	}
	rectangle VMH__S_NMS__S_BABS__S_01__F___N_KON__O_ as "VMH-NMS-BABS-01 (KON)" <<$server_generic_green>> {
		rectangle VMH__S_NMS__S_BABS__S_01__F__aA_NMS__F___S___F_Stao__F_A_aC_ as "VMH-NMS-BABS-01 [NMS - Stao A]" <<$virtual_application_server>> {
		
		}
	}
	rectangle VMH__S_NMS__S_BABS__S_02__F___N_KON__O_ as "VMH-NMS-BABS-02 (KON)" <<$server_generic_green>> {
		rectangle VMH__S_NMS__S_BABS__S_02__F__aA_NMS__F___S___F_Stao__F_A_aC_ as "VMH-NMS-BABS-02 [NMS - Stao A]" <<$virtual_application_server>> {
		
		}
	}
	rectangle MDC__S_NMS__S_BABS__S_00__F___N_KON__O_ as "MDC-NMS-BABS-00 (KON)" <<$server_generic_green>> {
		rectangle MDC__S_NMS__S_BABS__S_00__F___N_WIN__S_2016__S_STD__S_PHY__O_ as "MDC-NMS-BABS-00 (WIN-2016-STD-PHY)" <<$windows_server>> {
			rectangle MDC__S_NMS__S_BABS__S_00__F__aA_NMS__F___S___F_Stao__F_A_aC_ as "MDC-NMS-BABS-00 [NMS - Stao A]" <<$domain_controller>> {
			
			}
		}
	}
	rectangle PSA__S_NMS__S_BABS__S_00__F__aA_NMS__F___S___F_Stao__F_A_aC_ as "PSA-NMS-BABS-00 [NMS - Stao A]" <<$lock_with_key_security_blue>> {
	
	}
}


' Begin Protected Region [[layouting]]

' End Protected Region   [[layouting]]

@enduml
' Actifsource ID=[dc5bfacd-eaac-11e8-88d3-bfc6b992bdec,3a4a0f9c-0b72-11e9-a136-69d076e48ed1,Hash]
