@startuml


skinparam monochrome true
skinparam componentStyle uml2
actor IKT__F_Zentrale as "IKT Zentrale"
actor IKT__F_TN__S_Betreiber as "IKT TN-Betreiber"
actor System__S_Integrator as "System-Integrator"
actor Service__F_Desk as "Service Desk"
actor Sicherheitsverantwortlicher as "Sicherheitsverantwortlicher"
actor Betriebsmanagement as "Betriebsmanagement"
component IKT as "IKT" <<System>>
IKT__F_Zentrale -down-> IKT : operates
IKT__F_Zentrale -down-> IKT : monitors
IKT__F_Zentrale -down-> IKT : makeChanges
IKT__F_Zentrale -down-> IKT : adding
IKT__F_TN__S_Betreiber -down-> IKT : operates
IKT__F_TN__S_Betreiber -down-> IKT : monitors
System__S_Integrator -down-> IKT : develops
System__S_Integrator -down-> IKT : adding
Service__F_Desk -down-> IKT : monitors
Sicherheitsverantwortlicher -down-> IKT : secures
Sicherheitsverantwortlicher -down-> IKT : verifies

' Begin Protected Region [[layouting]]

' End Protected Region   [[layouting]]

@enduml
' Actifsource ID=[dc5bfacd-eaac-11e8-88d3-bfc6b992bdec,83a3855d-ff92-11e8-b134-df8d0a97667f,Hash]
