@startuml
skinparam monochrome true
skinparam componentStyle uml2
component FTP as "FTP" <<ExternalSystem>>
component Chess as "Chess" <<SoftwareSystem>>
FTP --> Chess : "verwendet"
Chess --> FTP : "verwendet"
' Begin Protected Region [[layouting]]

' End Protected Region   [[layouting]]
@enduml
// Actifsource ID=[dc5bfacd-eaac-11e8-88d3-bfc6b992bdec,35964cc6-fa45-11e8-af47-e5bdd8100025,Hash]
