@startuml

skinparam monochrome true
skinparam componentStyle uml2



show stereotype

rectangle Endpoint__F_Protection as "Endpoint Protection" <<SystemComponent>> {
}

rectangle Operating__F_System as "Operating System" <<SystemComponent>> {
}
Endpoint__F_Protection -down-> Operating__F_System : verwendet 

' Begin Protected Region [[layouting]]

' End Protected Region   [[layouting]]
@enduml
' Actifsource ID=[dc5bfacd-eaac-11e8-88d3-bfc6b992bdec,3b03bd0e-0e1a-11e9-8b4c-f9aec93d8b56,Hash]
