@startuml

skinparam monochrome true
skinparam componentStyle uml2


show stereotype

rectangle Proxy__F___N_PRX__O_ as "Proxy (PRX)" <<$reverse_proxy>> {
}

rectangle Windows__F___N_WIN__O_ as "Windows (WIN)" <<$windows_server>> {
}
Proxy__F___N_PRX__O_ -down-> Windows__F___N_WIN__O_ : verwendet 

' Begin Protected Region [[layouting]]

' End Protected Region   [[layouting]]
@enduml
' Actifsource ID=[dc5bfacd-eaac-11e8-88d3-bfc6b992bdec,241e13a5-0e1a-11e9-8b4c-f9aec93d8b56,Hash]
