@startuml

skinparam monochrome true
skinparam componentStyle uml2


show stereotype

rectangle Root__F_CA__F___N_MCR__O_ as "Root CA (MCR)" <<$certificate_authority>> {
}

rectangle Windows__F___N_WIN__O_ as "Windows (WIN)" <<$windows_server>> {
}
Root__F_CA__F___N_MCR__O_ -down-> Windows__F___N_WIN__O_ : verwendet 

' Begin Protected Region [[layouting]]

' End Protected Region   [[layouting]]
@enduml
' Actifsource ID=[dc5bfacd-eaac-11e8-88d3-bfc6b992bdec,34e45aed-0e1a-11e9-8b4c-f9aec93d8b56,Hash]
