@startuml

skinparam monochrome true
skinparam componentStyle uml2
component Tactilon as "Tactilon" <<ExternalSystem>>
component IP2__T_0 as "IP2.0" <<ExternalSystem>>
component PIC as "PIC" <<ExternalSystem>>
component MGW as "MGW" <<ExternalSystem>>
component Bundesschrank__F___N_BS__O_ as "Bundesschrank (BS)" <<ExternalSystem>>
component Nationalschrank__F___N_NS__O_ as "Nationalschrank (NS)" <<ExternalSystem>>
component IKT as "IKT" <<System>>
Tactilon --> IKT : "csr"
IP2__T_0 --> IKT : "csr"
IP2__T_0 --> IKT : "auth"
IP2__T_0 --> IKT : "radius"
PIC --> IKT : "cm"
PIC --> IKT : "repo"
PIC --> IKT : "certificate"
PIC --> IKT : "auth"
PIC --> IKT : "backup"
MGW --> IKT : "cm"
MGW --> IKT : "repo"
MGW --> IKT : "csr"
MGW --> IKT : "backup"
IKT --> Bundesschrank__F___N_BS__O_ : "space"
IKT --> Nationalschrank__F___N_NS__O_ : "space"
IKT --> IP2__T_0 : "networking"

' Begin Protected Region [[layouting]]

' End Protected Region   [[layouting]]
@enduml
' Actifsource ID=[dc5bfacd-eaac-11e8-88d3-bfc6b992bdec,ca171327-ef1d-11e8-be8a-b748ff8f0a75,Hash]
