chcp 65001
cmd /c bundle exec asciidoctor-pdf Chess.adoc
cmd /c bundle exec asciidoctor-pdf Readme.adoc
cmd /c bundle exec asciidoctor-pdf Sample_Requirements_Anforderungen.adoc
cmd /c bundle exec asciidoctor-pdf Sprint_1.adoc
cmd /c bundle exec asciidoctor-pdf My_Testing.adoc
cmd /c bundle exec asciidoctor-pdf Analyse_A.adoc
cmd /c bundle exec asciidoctor-pdf Analyse_B.adoc
cmd /c bundle exec asciidoctor-pdf TestReferenceArc42.adoc
cmd /c bundle exec asciidoctor-pdf Sprint_3.adoc
cmd /c bundle exec asciidoctor-pdf SampleArchitecture.adoc
cmd /c bundle exec asciidoctor-pdf AP01_WorkpackageSample.adoc
cmd /c bundle exec asciidoctor-pdf Sample_Planung.adoc
cmd /c bundle exec asciidoctor-pdf Hindernisse.adoc
cmd /c bundle exec asciidoctor-pdf Risikomanagement.adoc
cmd /c bundle exec asciidoctor-pdf Sample_Ressourcen.adoc
cmd /c bundle exec asciidoctor-pdf ProjectSample_Planung.adoc
cmd /c bundle exec asciidoctor-pdf AP02_Workpackage_B.adoc
cmd /c bundle exec asciidoctor-pdf F_higkeiten.adoc
cmd /c bundle exec asciidoctor-pdf TestSolutionArc42.adoc
