chcp 65001
cmd /c bundle exec asciidoctor -r asciidoctor-diagram -a data-uri cleon_collaboration_sample_doc_arc42/arc42.adoc
cmd /c bundle exec asciidoctor -r asciidoctor-diagram -a data-uri cleon_collaboration_sample_arc42/Chess_Architecture.adoc
cmd /c bundle exec asciidoctor -r asciidoctor-diagram -a data-uri cleon_collaboration_sample_analysis/Sample_Simple_Analyse.adoc
cmd /c bundle exec asciidoctor -r asciidoctor-diagram -a data-uri cleon_collaboration_sample_doc_reference/ReferenceDocumentWith___.adoc
cmd /c bundle exec asciidoctor -r asciidoctor-diagram -a data-uri cleon_collaboration_sample_sda_manuals_readme/Readme.adoc
cmd /c bundle exec asciidoctor -r asciidoctor-diagram -a data-uri cleon_collaboration_sample_eamod_chrv/Sample_Requirements_Anforderungen.adoc
cmd /c bundle exec asciidoctor -r asciidoctor-diagram -a data-uri cleon_collaboration_sample_planning/Sprint_1.adoc
cmd /c bundle exec asciidoctor -r asciidoctor-diagram -a data-uri testing/My_Testing.adoc
cmd /c bundle exec asciidoctor -r asciidoctor-diagram -a data-uri cleon_collaboration_sample_actifsource_actifsource_simple/Sample_Architecture.adoc
cmd /c bundle exec asciidoctor -r asciidoctor-diagram -a data-uri cleon_collaboration_sample_sda/Analyse_A.adoc
cmd /c bundle exec asciidoctor -r asciidoctor-diagram -a data-uri cleon_collaboration_sample_sda/Analyse_B.adoc
cmd /c bundle exec asciidoctor -r asciidoctor-diagram -a data-uri cleon_collaboration_sample_togaf/TestReferenceArc42_Architecture.adoc
cmd /c bundle exec asciidoctor -r asciidoctor-diagram -a data-uri cleon_collaboration_sample_planning/Sprint_3.adoc
cmd /c bundle exec asciidoctor -r asciidoctor-diagram -a data-uri cleon_collaboration_sample_software/SampleArchitecture_Architecture.adoc
cmd /c bundle exec asciidoctor -r asciidoctor-diagram -a data-uri cleon_collaboration_sample_planning/AP01_WorkpackageSample.adoc
cmd /c bundle exec asciidoctor -r asciidoctor-diagram -a data-uri cleon_collaboration_sample_planning/Sample_Planung.adoc
cmd /c bundle exec asciidoctor -r asciidoctor-diagram -a data-uri cleon_collaboration_sample_planning/Kontrolle_Sample_Planung.adoc
cmd /c bundle exec asciidoctor -r asciidoctor-diagram -a data-uri cleon_collaboration_sample_planning/Hindernisse_Sample_Planung.adoc
cmd /c bundle exec asciidoctor -r asciidoctor-diagram -a data-uri cleon_collaboration_sample_planning/Risikomanagement_Sample_Planung.adoc
cmd /c bundle exec asciidoctor -r asciidoctor-diagram -a data-uri cleon_collaboration_sample_planning/Sample_Ressourcen.adoc
cmd /c bundle exec asciidoctor -r asciidoctor-diagram -a data-uri cleon_collaboration_sample_planning/ConstraintProject_Planung.adoc
cmd /c bundle exec asciidoctor -r asciidoctor-diagram -a data-uri cleon_collaboration_sample_planning/AP02_Workpackage_B.adoc
cmd /c bundle exec asciidoctor -r asciidoctor-diagram -a data-uri cleon_collaboration_sample_eamod_ncv/F_higkeiten.adoc
cmd /c bundle exec asciidoctor -r asciidoctor-diagram -a data-uri cleon_collaboration_sample_togaf/TestSolutionArc42_Architecture.adoc
cmd /c bundle exec asciidoctor -r asciidoctor-diagram -a data-uri cleon_collaboration_sample_plattform/MyPlattform_Architecture.adoc
cmd /c bundle exec asciidoctor -r asciidoctor-diagram -a data-uri cleon_collaboration_sample_analysis/Sample_Requirements_Analyse.adoc
