chcp 65001
cmd /c bundle exec asciidoctor-pdf arc42.adoc
cmd /c bundle exec asciidoctor-pdf Chess_Architecture.adoc
cmd /c bundle exec asciidoctor-pdf Sample_Simple_Analyse.adoc
cmd /c bundle exec asciidoctor-pdf ReferenceDocumentWith___.adoc
cmd /c bundle exec asciidoctor-pdf Readme.adoc
cmd /c bundle exec asciidoctor-pdf Sample_Requirements_Anforderungen.adoc
cmd /c bundle exec asciidoctor-pdf Sprint_1.adoc
cmd /c bundle exec asciidoctor-pdf testing/My_Testing.adoc
cmd /c bundle exec asciidoctor-pdf Sample_Architecture.adoc
cmd /c bundle exec asciidoctor-pdf Analyse_A.adoc
cmd /c bundle exec asciidoctor-pdf Analyse_B.adoc
cmd /c bundle exec asciidoctor-pdf TestReferenceArc42_Architecture.adoc
cmd /c bundle exec asciidoctor-pdf Sprint_3.adoc
cmd /c bundle exec asciidoctor-pdf SampleArchitecture_Architecture.adoc
cmd /c bundle exec asciidoctor-pdf AP01_WorkpackageSample.adoc
cmd /c bundle exec asciidoctor-pdf Sample_Planung.adoc
cmd /c bundle exec asciidoctor-pdf Kontrolle_Sample_Planung.adoc
cmd /c bundle exec asciidoctor-pdf Hindernisse_Sample_Planung.adoc
cmd /c bundle exec asciidoctor-pdf Risikomanagement_Sample_Planung.adoc
cmd /c bundle exec asciidoctor-pdf Sample_Ressourcen.adoc
cmd /c bundle exec asciidoctor-pdf ConstraintProject_Planung.adoc
cmd /c bundle exec asciidoctor-pdf AP02_Workpackage_B.adoc
cmd /c bundle exec asciidoctor-pdf F_higkeiten.adoc
cmd /c bundle exec asciidoctor-pdf TestSolutionArc42_Architecture.adoc
cmd /c bundle exec asciidoctor-pdf MyPlattform_Architecture.adoc
cmd /c bundle exec asciidoctor-pdf Sample_Requirements_Analyse.adoc
