chcp 65001
cmd /c bundle exec asciidoctor-pdf cleon_projectmethods_hermes_sample_detailstudy/Sample_Simple_Analyse_Detailstudie.adoc
cmd /c bundle exec asciidoctor-pdf cleon_projectmethods_hermes_sample_projectmanagement/Sample_Ressourcen.adoc
cmd /c bundle exec asciidoctor-pdf cleon_projectmethods_hermes_sample_projectmanagement/20180312_My_Protocol/20180312_My_Protocol.adoc
cmd /c bundle exec asciidoctor-pdf cleon_projectmethods_hermes_sample_projectmanagement/Sample_Planung.adoc
