:toc-title: Table of Contents
:toc:
:numbered:
[[section-Introduction_and_Goals]]
== Introduction and Goals
// Begin Protected Region [[starting]]

// End Protected Region   [[starting]]


The introduction to the architecture documentation should list the driving forces that software architects must consider in their decisions.
This includes on the one hand the fulfillment of functional requirements of the stakeholders, on the other hand the fulfillment of or compliance with required constraints, always in consideration of the architecture goals.

=== Requirements Overview

[role="arc42help"]
****
Short description of the functional requirements.
Digest (or abstract) of the requirements documents.
Reference to complete requirements documents (incl. version identification and location).
.Contents
A compact summary of the functional environment of the system. Answers the following questions (at least approximately):
. What happens in the systems environment?
. Why should the system exist? 
. Why is the system valuable or important? 
. Which problems does the system solve?
.Motivation
From the point of view of the end users a system is created or modified to improve execution of a business activity.
This essential architecture driver must not be neglected even though the quality of an architecture is mostly judged by its level of fulfillment of non-functional requirements.
.Form
Short textual description, probably in tabular use-case format.
The business context should in any case refer to the corresponding requirements documents.
.Examples
Short descriptions of the most important:
**** 

// Begin Protected Region [[ending]]

// End Protected Region   [[ending]]
// Actifsource ID=[dd9c4f30-d871-11e4-aa2f-c11242a92b60,6f09b217-3088-11e5-8cdc-d5b441c8c3df,tib5ExOgBo8gYgAM2ixhH7EcBr4=]
