= Chess
:toc-title: Inhaltsverzeichnis
:toc: left
:numbered:
:imagesdir: ..
:imagesdir: ./img
:imagesoutdir: ./img




== Einführung und Ziele




=== QualityGoals








== Bausteinsicht




=== Chess








== Verteilsicht







== Kontextabgrenzung



In diesem Kapitel wird der Kontext betrachteten Systems (Chess) aufgeführt. 

Die nachfolgende Tabelle beschreibt die Nachbarsysteme an das betrachtete System.

[cols="5,10a" options="header"]
|====
|Name | Beschreibung
|Table
|
World
|====
=== Fachlicher Kontext



In diesem Kapitel werden die Aktoren (Actor) und Nachbarsysteme (Neighboring) des betrachteten Systems (Chess) aufgeführt. 

[plantuml, png]
....
skinparam monochrome true
component "Chess" #grey
actor "Player A"
component "Table"
(Player A) <-- (Chess) : definiert
(Player A) <-- (FTP) : ruft
....

Die nachfolgende Tabelle beschreibt die Aktoren an das betrachtete System.

[cols="5,10a" options="header"]
|====
|Name | Beschreibung
|Player A
|
Gugeli
|====

Die nachfolgende Tabelle beschreibt die Kommunikationsflüsse (Flows) zwischen allen Teilnehmern.

[cols="5,5,5,5,10a" options="header"]
|====
|Von | Zu | Interaktion | Richtung | Beschreibung
|Player A
|Chess
|definiert
|<--
|
asdfadf
|Player A
|FTP
|ruft
|<--
|
ddd
|====


=== Technischer Kontext



In diesem Kapitel werden die Schnittstellen an die Nachbarsysteme (Neighboring) des betrachteten Systems (Chess) aufgeführt. 

[plantuml, png]
....
skinparam monochrome true
component "Chess" #grey
component "FTP"
component "Table"
(FTP) --> (Chess) : ssss
....

Die nachfolgende Tabelle beschreibt die Schnittstellen an das betrachtete System.

[cols="5,10a" options="header"]
|====
|Name | Beschreibung
|FTP
|
dsfasdf
|====

Die nachfolgende Tabelle beschreibt die Kommunikationsflüsse (Flows) zwischen allen Teilnehmern.

[cols="5,5,5,5,10a" options="header"]
|====
|Von | Zu | Interaktion | Richtung | Beschreibung
|FTP
|Chess
|ssss
|-->
|
ddd
|====


=== Chess









