= ConstraintProject Planung
:toc-title: Inhaltsverzeichnis
:toc: left
:numbered:
:imagesdir: ..
:imagesdir: ./img
:imagesoutdir: ./img



== Ziele


=== Projektziele



=== Systemziele



== Lieferumfang



== Zeitplan


=== Kalender

==== 2016.1

[cols="3,3,3,3,3"]
|===

|
{set:cellbgcolor:#ffffff}
*1*

Meilensteine (Start)

Meilensteine (Start)

2016-01-01_Fri_Sprint Review 2 (Termin)

2016-01-01_Fri_Sprint Retospektive 2 (Termin)



|
{set:cellbgcolor:#d3d3d3}
*2*

Sprint 2 (Start)

Sprint 2 (Ende)

2016-01-02_Sat_Workshop (Termin)



|
{set:cellbgcolor:#d3d3d3}
*3*



|
{set:cellbgcolor:#ffffff}
*4*



|
{set:cellbgcolor:#ffffff}
*5*

Meilensteine (Ende)



|
{set:cellbgcolor:#ffffff}
*6*

Pascal Meier abwesend (Vacation)



|
{set:cellbgcolor:#ffffff}
*7*

Pascal Meier abwesend (Vacation)



|
{set:cellbgcolor:#ffffff}
*8*

Pascal Meier abwesend (Vacation)



|
{set:cellbgcolor:#d3d3d3}
*9*



|
{set:cellbgcolor:#d3d3d3}
*10*



|
{set:cellbgcolor:#ffffff}
*11*



|
{set:cellbgcolor:#ffffff}
*12*



|
{set:cellbgcolor:#ffffff}
*13*



|
{set:cellbgcolor:#ffffff}
*14*



|
{set:cellbgcolor:#ffffff}
*15*



|
{set:cellbgcolor:#d3d3d3}
*16*

Pascal Meier abwesend (Free)



|
{set:cellbgcolor:#d3d3d3}
*17*



|
{set:cellbgcolor:#ffffff}
*18*



|
{set:cellbgcolor:#ffffff}
*19*



|
{set:cellbgcolor:#ffffff}
*20*



|
{set:cellbgcolor:#ffffff}
*21*

Sprint 1 (Start)

Patrick Meier abwesend (Free)



|
{set:cellbgcolor:#ffffff}
*22*



|
{set:cellbgcolor:#d3d3d3}
*23*



|
{set:cellbgcolor:#d3d3d3}
*24*



|
{set:cellbgcolor:#ffffff}
*25*



|
{set:cellbgcolor:#ffffff}
*26*



|
{set:cellbgcolor:#ffffff}
*27*



|
{set:cellbgcolor:#ffffff}
*28*



|
{set:cellbgcolor:#ffffff}
*29*



|
{set:cellbgcolor:#d3d3d3}
*30*



|
{set:cellbgcolor:#d3d3d3}
*31*


{set:cellbgcolor:none}	
||||

|===


=== Meilensteine


Berechnete Velocity (alle Sprints): 

==== Konzeptphase


===== Release MS20


[cols="10,20"]
|===
|*Startdatum*|
|*Enddatum*|
|===


// Actifsource ID=[dd9c4f30-d871-11e4-aa2f-c11242a92b60,8fe2772a-d434-11e6-8a1d-7fdd5d29730e,Hash]
