= Chess_Architecture
:toc-title: Inhaltsverzeichnis
:toc: left
:numbered:
:imagesdir: ..
:imagesdir: ./img
:imagesoutdir: ./img



== Einführung und Ziele


=== Qualitätsziele



=== Aufgabenstellung



== Randbedingungen


=== Technische Randbedingungen



=== Organisatorische Randbedingungen



== Kontextabgrenzung


In diesem Kapitel wird der Kontext betrachteten Systems (Chess) aufgeführt.
=== Fachlicher Kontext
<db:para>In diesem Kapitel werden die Aktoren (Actor) des betrachteten Systems (Chess) aufgeführt.</db:para>

[plantuml, png]
....
skinparam monochrome true
skinparam componentStyle uml2
actor Player__F_A as "Player A"
actor Player__F_B as "Player B"
component Chess as "Chess" <<SoftwareSystem>>
Chess -up-> Player__F_A : gets
Player__F_A -down-> Chess : interacts
Player__F_B -down-> Chess : interacts
...
Die nachfolgende Tabelle beschreibt die Aktoren an das betrachtete System.
[cols="40,60a" options="header"]
|====
|Aktor | Beschreibung
|Player A
|Player B
|====
Die nachfolgende Tabelle beschreibt die Kommunikationsflüsse (Flows) zwischen allen Teilnehmern und dem System.
[cols="15,15,20,50a" options="header"]
|====
|Von | Zu | Interaktion | Beschreibung
|Chess
|Player A
|gets
|Player A
|Chess
|interacts

|Player B
|Chess
|interacts

|====

=== Technischer Kontext

[plantuml, png]
....
skinparam monochrome true
skinparam componentStyle uml2
component FTP as "FTP" <<ExternalSystem>>
component Chess as "Chess" <<SoftwareSystem>>
FTP --> Chess : "verwendet"
Chess --> FTP : "verwendet"
...
In diesem Kapitel werden die Schnittstellen an die Nachbarsysteme (Neighboring) des betrachteten Systems (Chess) aufgeführt. 

Die nachfolgende Tabelle beschreibt die Schnittstellen an das betrachtete System.

[cols="5,10a" options="header"]
|====
|Name | Beschreibung
|FTP
|
dsfasdf
|====

Die nachfolgende Tabelle beschreibt die Kommunikationsflüsse (Flows) zwischen allen Teilnehmern.

[cols="5,5,5,5,10a" options="header"]
|====
|Von | Zu | Interaktion | Richtung | Beschreibung
|====

== Bausteinsicht


=== Ebene 1: Chess <SoftwareSystem> (Whitebox)


==== Test1 <SampleBuildingBlock> (Blackbox)


===== Abhängigkeiten



===== Anforderungsabdeckung



==== Test2 <SampleBuildingBlock> (Blackbox)


===== Abhängigkeiten



===== Anforderungsabdeckung



==== Test3 <SampleBuildingBlock> (Blackbox)


===== Abhängigkeiten



===== Anforderungsabdeckung



== Verteilsicht


=== Bauen



=== Paketierung



=== Verteilung



=== Test



=== Überwachung



== Entwurfsentscheidungen


=== Entwurfsentscheidung Einsatz von PAM in AD 



=== Entwurfsentscheidung dsfsdf 



== Qualitätsszenarios



== Risiken und technische Schulden



= Glossar


ikt_1:: 
	blababasdasd
	asdaSDASDADS
	ASDASD

ikt_2:: 



// Actifsource ID=[dd9c4f30-d871-11e4-aa2f-c11242a92b60,bb88c324-11f5-11e5-848b-017a3a98ae34,Hash]
