// Begin Protected Region [[meta-data]]

// End Protected Region   [[meta-data]]

:toc:

[#15f3cc95-ea44-11f0-abd2-39998c8c9596]
=== Level_2: ServiceLayer <ServicesLayer> (Whitebox)
Motivation::
Fullname::
microservicesample.servicelayer

Parent::
<<#f194c1a0-cb08-11f0-ad08-33c52acb975f>>

==== Building Block Overview

The ServiceLayer is decomposed into the following components:

[plantuml, Ebene_2: ServiceLayer <ServicesLayer> (Whitebox)BlockOverview, format="svg"]
----
@startuml Ebene_2: ServiceLayer <ServicesLayer> (Whitebox)BuildingBlockOverview

skinparam ranksep 10
skinparam componentStyle rectangle
skinparam shadowing false
skinparam arrowColor lightblue
skinparam arrowThickness 1.2
skinparam rectangle {
  BackgroundColor White
  BorderColor #333
  RoundCorner 10
}
top to bottom direction

component "Ebene_1: MicroserviceSample (MicroserviceSample) <SoftwareArchitecturePattern> (Whitebox) (Parent)" {
    component "Ebene_2: ServiceLayer <ServicesLayer> (Whitebox)" #lightblue {
        [**Ebene_3: Test Sample 1Service <ServiceComponent> (Whitebox)**] as 1A37904D_EA44_11F0_ABD2_39998C8C9596
    }
}

@enduml
----

. Test Sample 1Service (<<#1a37904d-ea44-11f0-abd2-39998c8c9596>>)


// Begin Protected Region [[15f3cc95-ea44-11f0-abd2-39998c8c9596,customText]]

// End Protected Region   [[15f3cc95-ea44-11f0-abd2-39998c8c9596,customText]]

// Begin Protected Region [[motivation]]
TODO: Describe the motivation for the building block view.
// End Protected Region   [[motivation]]
// Begin Protected Region [[4147fc8e-e5a0-11f0-a60c-db015d172622,interface]]
TODO: Describe the interface(s).
// End Protected Region   [[4147fc8e-e5a0-11f0-a60c-db015d172622,interface]]
// Begin Protected Region [[4147fc8e-e5a0-11f0-a60c-db015d172622,quality]]
TODO: Describe the quality/performance characteristics.
// End Protected Region   [[4147fc8e-e5a0-11f0-a60c-db015d172622,quality]]
// Begin Protected Region [[4147fc8e-e5a0-11f0-a60c-db015d172622,reqs]]
TODO: Describe the fulfilled requirements.
// End Protected Region   [[4147fc8e-e5a0-11f0-a60c-db015d172622,reqs]]
// Begin Protected Region [[4147fc8e-e5a0-11f0-a60c-db015d172622,location]]
TODO: Describe the directory/file location.
// End Protected Region   [[4147fc8e-e5a0-11f0-a60c-db015d172622,location]]
// Begin Protected Region [[4147fc8e-e5a0-11f0-a60c-db015d172622,issues]]
TODO: Describe the open issues/problems/risks.
// End Protected Region   [[4147fc8e-e5a0-11f0-a60c-db015d172622,issues]]
// Actifsource ID=[803ac313-d64b-11ee-8014-c150876d6b6e,15f3cc95-ea44-11f0-abd2-39998c8c9596,dd79cee8-3339-11e8-a9fe-87ba35d8f5c4,15f3cc95-ea44-11f0-abd2-39998c8c9596,0GNymaJy+Zcy5lkyzlIU67CQgfA=]
