@startuml

skinparam monochrome true
skinparam componentStyle uml2
left to right direction

!include <tupadr3/common>
!include <office/Servers/database_server>
!include <office/Servers/application_server>
!include <office/Security/domain>
!include <office/Servers/domain_controller>
!include <office/Servers/physical_host_solid_blue>

show stereotype

rectangle IKT as "IKT (Ebene 1)" <<System>> {
	rectangle Infrastruktur as "Infrastruktur (Ebene 2)" <<SystemLayer>> {
		rectangle Operating_System as "Operating System (Ebene 3)" <<SystemComponent>> {
		}
		rectangle Storage as "Storage (Ebene 3)" <<SystemComponent>> {
		}
		rectangle Physical_Compute as "Physical Compute (Ebene 3)" <<SystemComponent>> {
		}
		rectangle Virtual_Compute as "Virtual Compute (Ebene 3)" <<SystemComponent>> {
		}
		rectangle Network as "Network (Ebene 3)" <<SystemComponent>> {
		}
	}		
	rectangle Plattform as "Plattform (Ebene 2)" <<SystemLayer>> {
		rectangle Application as "Application (Ebene 3)" <<SystemComponent>> {
		}
		rectangle Datenablage as "Datenablage (Ebene 3)" <<SystemComponent>> {
		}
	}		
	rectangle Management as "Management (Ebene 2)" <<SystemLayer>> {
		rectangle Hypervisor_Management as "Hypervisor Management (Ebene 3)" <<SystemComponent>> {
		}
		rectangle Backup_Management as "Backup Management (Ebene 3)" <<SystemComponent>> {
		}
		rectangle Jump_Host as "Jump Host (Ebene 3)" <<SystemComponent>> {
		}
		rectangle Deployment as "Deployment (Ebene 3)" <<SystemComponent>> {
		}
		rectangle Monitoring as "Monitoring (Ebene 3)" <<SystemComponent>> {
		}
	}		
	rectangle Security as "Security (Ebene 2)" <<SystemLayer>> {
		rectangle Directory_Services as "Directory Services (Ebene 3)" <<SystemComponent>> {
		}
		rectangle Identity_Access_Management as "Identity Access Management (Ebene 3)" <<SystemComponent>> {
		}
		rectangle PKI as "PKI (Ebene 3)" <<SystemComponent>> {
		}
		rectangle Endpoint_Protection as "Endpoint Protection (Ebene 3)" <<SystemComponent>> {
		}
	}		

	Plattform --> Infrastruktur : "verwendet"
	Management --> Plattform : "verwendet"
	Security --> Plattform : "verwendet"


}

' Begin Protected Region [[layouting]]

' End Protected Region   [[layouting]]
@enduml
' Actifsource ID=[dc5bfacd-eaac-11e8-88d3-bfc6b992bdec,c65eee82-035e-11e9-9e58-33d596257b14,Hash]
