@startuml

skinparam monochrome true
skinparam componentStyle uml2

















show stereotype

rectangle Infrastruktur as "Infrastruktur" <<SystemLayer>> {
	rectangle Operating__F_System as "Operating System" <<SystemComponent>> {
	}		
	rectangle Storage as "Storage" <<SystemComponent>> {
	}		
	rectangle Physical__F_Compute as "Physical Compute" <<SystemComponent>> {
	}		
	rectangle Virtual__F_Compute as "Virtual Compute" <<SystemComponent>> {
	}		
	rectangle Network as "Network" <<SystemComponent>> {
	}		

}

' Begin Protected Region [[layouting]]

' End Protected Region   [[layouting]]
@enduml
' Actifsource ID=[dc5bfacd-eaac-11e8-88d3-bfc6b992bdec,53bc2ee2-0a94-11e9-9f72-e5610a9d4cd3,Hash]
