@startuml

skinparam monochrome true
skinparam componentStyle uml2


















































show stereotype

rectangle IKT as "IKT" <<SystemWithLayers>> {
	rectangle Infrastruktur as "Infrastruktur" <<SystemLayer>> {
	}		
	rectangle Plattform as "Plattform" <<SystemLayer>> {
	}		
	rectangle Management as "Management" <<SystemLayer>> {
	}		
	rectangle Security as "Security" <<SystemLayer>> {
	}		

}

' Begin Protected Region [[layouting]]

' End Protected Region   [[layouting]]
@enduml
' Actifsource ID=[dc5bfacd-eaac-11e8-88d3-bfc6b992bdec,7c2facb3-0a93-11e9-9f72-e5610a9d4cd3,Hash]
