= Sample Planung
:toc-title: Inhaltsverzeichnis
:toc: left
:numbered:
:imagesdir: ..
:imagesdir: ./img
:imagesoutdir: ./img




== Ausgangslage




=== Ausgangslage A






=== Ausgangslage B







== Ziele




=== Projektziele






=== Systemziele







== Abhängigkeiten und Abgrenzungen




=== Abhängigkeiten






=== Abgrenzungen







== Lieferumfang




=== Lieferobjekte



[cols="5,5,10", options="header"]
|===
|Name|Abkürzung|Beschreibung
|LO01_Document 1
|short 
|
|LO02_System 1
|
|
|===


=== Lieferergebnisse




==== LE03_System 1_[B]_1.1.0



[cols="5,10"]
|===
|Status|Open
|Verantwortlicher|Pascal Meier
|===



==== LE02_Document 1_[Draft]_1.0.0



[cols="5,10"]
|===
|Status|Done
|Verantwortlicher|Pascal Meier
|===

[cols="5,10a" options="header"]
.Lieferergebnis Abhängigkeiten
|===
|Abhängigkeit|Begründung
|LE03_System 1_[B]_1.1.0
|
|===




== Zeitplan



=== Kalender

==== 2016.1

[cols="3,3,3,3,3"]
|===

|
{set:cellbgcolor:#ffffff}
*1*

Meilensteine (Start)

Meilensteine (Start)

2016-01-01_Fri_Sprint Review 2 (Termin)

2016-01-01_Fri_Sprint Retospektive 2 (Termin)



|
{set:cellbgcolor:#d3d3d3}
*2*

Sprint 2 (Start)

Sprint 2 (Ende)

2016-01-02_Sat_Workshop (Termin)



|
{set:cellbgcolor:#d3d3d3}
*3*



|
{set:cellbgcolor:#ffffff}
*4*



|
{set:cellbgcolor:#ffffff}
*5*

Meilensteine (Ende)



|
{set:cellbgcolor:#ffffff}
*6*

Pascal Meier abwesend (Vacation)



|
{set:cellbgcolor:#ffffff}
*7*

Pascal Meier abwesend (Vacation)



|
{set:cellbgcolor:#ffffff}
*8*

Pascal Meier abwesend (Vacation)



|
{set:cellbgcolor:#d3d3d3}
*9*



|
{set:cellbgcolor:#d3d3d3}
*10*



|
{set:cellbgcolor:#ffffff}
*11*



|
{set:cellbgcolor:#ffffff}
*12*



|
{set:cellbgcolor:#ffffff}
*13*



|
{set:cellbgcolor:#ffffff}
*14*



|
{set:cellbgcolor:#ffffff}
*15*



|
{set:cellbgcolor:#d3d3d3}
*16*

Pascal Meier abwesend (Free)



|
{set:cellbgcolor:#d3d3d3}
*17*



|
{set:cellbgcolor:#ffffff}
*18*



|
{set:cellbgcolor:#ffffff}
*19*



|
{set:cellbgcolor:#ffffff}
*20*



|
{set:cellbgcolor:#ffffff}
*21*

Sprint 1 (Start)

Patrick Meier abwesend (Free)



|
{set:cellbgcolor:#ffffff}
*22*



|
{set:cellbgcolor:#d3d3d3}
*23*



|
{set:cellbgcolor:#d3d3d3}
*24*



|
{set:cellbgcolor:#ffffff}
*25*



|
{set:cellbgcolor:#ffffff}
*26*



|
{set:cellbgcolor:#ffffff}
*27*



|
{set:cellbgcolor:#ffffff}
*28*



|
{set:cellbgcolor:#ffffff}
*29*



|
{set:cellbgcolor:#d3d3d3}
*30*



|
{set:cellbgcolor:#d3d3d3}
*31*


{set:cellbgcolor:none}	
||||

|===

==== 2016.2

[cols="3,3,3,3,3"]
|===

|
{set:cellbgcolor:#ffffff}
*1*



|
{set:cellbgcolor:#ffffff}
*2*



|
{set:cellbgcolor:#ffffff}
*3*

Sprint 1 (Ende)



|
{set:cellbgcolor:#ffffff}
*4*



|
{set:cellbgcolor:#ffffff}
*5*



|
{set:cellbgcolor:#d3d3d3}
*6*



|
{set:cellbgcolor:#d3d3d3}
*7*



|
{set:cellbgcolor:#ffffff}
*8*



|
{set:cellbgcolor:#ffffff}
*9*



|
{set:cellbgcolor:#ffffff}
*10*



|
{set:cellbgcolor:#ffffff}
*11*



|
{set:cellbgcolor:#ffffff}
*12*



|
{set:cellbgcolor:#d3d3d3}
*13*



|
{set:cellbgcolor:#d3d3d3}
*14*



|
{set:cellbgcolor:#ffffff}
*15*



|
{set:cellbgcolor:#ffffff}
*16*



|
{set:cellbgcolor:#ffffff}
*17*



|
{set:cellbgcolor:#ffffff}
*18*



|
{set:cellbgcolor:#ffffff}
*19*



|
{set:cellbgcolor:#d3d3d3}
*20*



|
{set:cellbgcolor:#d3d3d3}
*21*



|
{set:cellbgcolor:#ffffff}
*22*



|
{set:cellbgcolor:#ffffff}
*23*



|
{set:cellbgcolor:#ffffff}
*24*



|
{set:cellbgcolor:#ffffff}
*25*



|
{set:cellbgcolor:#ffffff}
*26*



|
{set:cellbgcolor:#d3d3d3}
*27*



|
{set:cellbgcolor:#d3d3d3}
*28*



|
{set:cellbgcolor:#ffffff}
*29*


{set:cellbgcolor:none}	
|

|===

==== 2016.3

[cols="3,3,3,3,3"]
|===

|
{set:cellbgcolor:#ffffff}
*1*



|
{set:cellbgcolor:#ffffff}
*2*



|
{set:cellbgcolor:#ffffff}
*3*



|
{set:cellbgcolor:#ffffff}
*4*



|
{set:cellbgcolor:#d3d3d3}
*5*



|
{set:cellbgcolor:#d3d3d3}
*6*



|
{set:cellbgcolor:#ffffff}
*7*



|
{set:cellbgcolor:#ffffff}
*8*



|
{set:cellbgcolor:#ffffff}
*9*



|
{set:cellbgcolor:#ffffff}
*10*



|
{set:cellbgcolor:#ffffff}
*11*



|
{set:cellbgcolor:#d3d3d3}
*12*



|
{set:cellbgcolor:#d3d3d3}
*13*



|
{set:cellbgcolor:#ffffff}
*14*



|
{set:cellbgcolor:#ffffff}
*15*



|
{set:cellbgcolor:#ffffff}
*16*



|
{set:cellbgcolor:#ffffff}
*17*



|
{set:cellbgcolor:#ffffff}
*18*



|
{set:cellbgcolor:#d3d3d3}
*19*



|
{set:cellbgcolor:#d3d3d3}
*20*



|
{set:cellbgcolor:#ffffff}
*21*



|
{set:cellbgcolor:#ffffff}
*22*



|
{set:cellbgcolor:#ffffff}
*23*



|
{set:cellbgcolor:#ffffff}
*24*



|
{set:cellbgcolor:#ffffff}
*25*



|
{set:cellbgcolor:#d3d3d3}
*26*



|
{set:cellbgcolor:#d3d3d3}
*27*



|
{set:cellbgcolor:#ffffff}
*28*



|
{set:cellbgcolor:#ffffff}
*29*



|
{set:cellbgcolor:#ffffff}
*30*



|
{set:cellbgcolor:#ffffff}
*31*


{set:cellbgcolor:none}	
||||

|===

==== 2016.4

[cols="3,3,3,3,3"]
|===

|
{set:cellbgcolor:#ffffff}
*1*



|
{set:cellbgcolor:#d3d3d3}
*2*



|
{set:cellbgcolor:#d3d3d3}
*3*



|
{set:cellbgcolor:#ffffff}
*4*



|
{set:cellbgcolor:#ffffff}
*5*



|
{set:cellbgcolor:#ffffff}
*6*



|
{set:cellbgcolor:#ffffff}
*7*



|
{set:cellbgcolor:#ffffff}
*8*



|
{set:cellbgcolor:#d3d3d3}
*9*



|
{set:cellbgcolor:#d3d3d3}
*10*



|
{set:cellbgcolor:#ffffff}
*11*



|
{set:cellbgcolor:#ffffff}
*12*



|
{set:cellbgcolor:#ffffff}
*13*



|
{set:cellbgcolor:#ffffff}
*14*



|
{set:cellbgcolor:#ffffff}
*15*



|
{set:cellbgcolor:#d3d3d3}
*16*



|
{set:cellbgcolor:#d3d3d3}
*17*



|
{set:cellbgcolor:#ffffff}
*18*



|
{set:cellbgcolor:#ffffff}
*19*



|
{set:cellbgcolor:#ffffff}
*20*



|
{set:cellbgcolor:#ffffff}
*21*



|
{set:cellbgcolor:#ffffff}
*22*



|
{set:cellbgcolor:#d3d3d3}
*23*



|
{set:cellbgcolor:#d3d3d3}
*24*



|
{set:cellbgcolor:#ffffff}
*25*



|
{set:cellbgcolor:#ffffff}
*26*



|
{set:cellbgcolor:#ffffff}
*27*



|
{set:cellbgcolor:#ffffff}
*28*



|
{set:cellbgcolor:#ffffff}
*29*



|
{set:cellbgcolor:#d3d3d3}
*30*


{set:cellbgcolor:none}	
|||||

|===

==== 2016.5

[cols="3,3,3,3,3"]
|===

|
{set:cellbgcolor:#d3d3d3}
*1*



|
{set:cellbgcolor:#ffffff}
*2*



|
{set:cellbgcolor:#ffffff}
*3*



|
{set:cellbgcolor:#ffffff}
*4*



|
{set:cellbgcolor:#ffffff}
*5*



|
{set:cellbgcolor:#ffffff}
*6*



|
{set:cellbgcolor:#d3d3d3}
*7*



|
{set:cellbgcolor:#d3d3d3}
*8*



|
{set:cellbgcolor:#ffffff}
*9*



|
{set:cellbgcolor:#ffffff}
*10*



|
{set:cellbgcolor:#ffffff}
*11*



|
{set:cellbgcolor:#ffffff}
*12*



|
{set:cellbgcolor:#ffffff}
*13*



|
{set:cellbgcolor:#d3d3d3}
*14*



|
{set:cellbgcolor:#d3d3d3}
*15*



|
{set:cellbgcolor:#ffffff}
*16*



|
{set:cellbgcolor:#ffffff}
*17*



|
{set:cellbgcolor:#ffffff}
*18*



|
{set:cellbgcolor:#ffffff}
*19*



|
{set:cellbgcolor:#ffffff}
*20*



|
{set:cellbgcolor:#d3d3d3}
*21*



|
{set:cellbgcolor:#d3d3d3}
*22*



|
{set:cellbgcolor:#ffffff}
*23*



|
{set:cellbgcolor:#ffffff}
*24*



|
{set:cellbgcolor:#ffffff}
*25*



|
{set:cellbgcolor:#ffffff}
*26*



|
{set:cellbgcolor:#ffffff}
*27*

Sprint 3 (Start)



|
{set:cellbgcolor:#d3d3d3}
*28*



|
{set:cellbgcolor:#d3d3d3}
*29*



|
{set:cellbgcolor:#ffffff}
*30*



|
{set:cellbgcolor:#ffffff}
*31*


{set:cellbgcolor:none}	
||||

|===

==== 2016.6

[cols="3,3,3,3,3"]
|===

|
{set:cellbgcolor:#ffffff}
*1*



|
{set:cellbgcolor:#ffffff}
*2*



|
{set:cellbgcolor:#ffffff}
*3*



|
{set:cellbgcolor:#d3d3d3}
*4*



|
{set:cellbgcolor:#d3d3d3}
*5*



|
{set:cellbgcolor:#ffffff}
*6*



|
{set:cellbgcolor:#ffffff}
*7*



|
{set:cellbgcolor:#ffffff}
*8*



|
{set:cellbgcolor:#ffffff}
*9*



|
{set:cellbgcolor:#ffffff}
*10*



|
{set:cellbgcolor:#d3d3d3}
*11*



|
{set:cellbgcolor:#d3d3d3}
*12*



|
{set:cellbgcolor:#ffffff}
*13*



|
{set:cellbgcolor:#ffffff}
*14*



|
{set:cellbgcolor:#ffffff}
*15*



|
{set:cellbgcolor:#ffffff}
*16*



|
{set:cellbgcolor:#ffffff}
*17*



|
{set:cellbgcolor:#d3d3d3}
*18*



|
{set:cellbgcolor:#d3d3d3}
*19*



|
{set:cellbgcolor:#ffffff}
*20*



|
{set:cellbgcolor:#ffffff}
*21*

Sprint 3 (Ende)



|
{set:cellbgcolor:#ffffff}
*22*

Sprint 4 (Start)



|
{set:cellbgcolor:#ffffff}
*23*



|
{set:cellbgcolor:#ffffff}
*24*



|
{set:cellbgcolor:#d3d3d3}
*25*



|
{set:cellbgcolor:#d3d3d3}
*26*



|
{set:cellbgcolor:#ffffff}
*27*



|
{set:cellbgcolor:#ffffff}
*28*



|
{set:cellbgcolor:#ffffff}
*29*



|
{set:cellbgcolor:#ffffff}
*30*


{set:cellbgcolor:none}	
|||||

|===

==== 2016.7

[cols="3,3,3,3,3"]
|===

|
{set:cellbgcolor:#ffffff}
*1*



|
{set:cellbgcolor:#d3d3d3}
*2*



|
{set:cellbgcolor:#d3d3d3}
*3*



|
{set:cellbgcolor:#ffffff}
*4*



|
{set:cellbgcolor:#ffffff}
*5*

Sprint 4 (Ende)



|
{set:cellbgcolor:#ffffff}
*6*

Sprint 5 (Start)



|
{set:cellbgcolor:#ffffff}
*7*



|
{set:cellbgcolor:#ffffff}
*8*



|
{set:cellbgcolor:#d3d3d3}
*9*



|
{set:cellbgcolor:#d3d3d3}
*10*



|
{set:cellbgcolor:#ffffff}
*11*



|
{set:cellbgcolor:#ffffff}
*12*



|
{set:cellbgcolor:#ffffff}
*13*



|
{set:cellbgcolor:#ffffff}
*14*



|
{set:cellbgcolor:#ffffff}
*15*



|
{set:cellbgcolor:#d3d3d3}
*16*



|
{set:cellbgcolor:#d3d3d3}
*17*



|
{set:cellbgcolor:#ffffff}
*18*



|
{set:cellbgcolor:#ffffff}
*19*

Sprint 5 (Ende)



|
{set:cellbgcolor:#ffffff}
*20*

Sprint 6 (Start)



|
{set:cellbgcolor:#ffffff}
*21*



|
{set:cellbgcolor:#ffffff}
*22*



|
{set:cellbgcolor:#d3d3d3}
*23*



|
{set:cellbgcolor:#d3d3d3}
*24*



|
{set:cellbgcolor:#ffffff}
*25*



|
{set:cellbgcolor:#ffffff}
*26*



|
{set:cellbgcolor:#ffffff}
*27*



|
{set:cellbgcolor:#ffffff}
*28*



|
{set:cellbgcolor:#ffffff}
*29*



|
{set:cellbgcolor:#d3d3d3}
*30*



|
{set:cellbgcolor:#d3d3d3}
*31*


{set:cellbgcolor:none}	
||||

|===

==== 2016.8

[cols="3,3,3,3,3"]
|===

|
{set:cellbgcolor:#ffffff}
*1*



|
{set:cellbgcolor:#ffffff}
*2*

Sprint 6 (Ende)



|
{set:cellbgcolor:#ffffff}
*3*

Sprint 7 (Start)



|
{set:cellbgcolor:#ffffff}
*4*



|
{set:cellbgcolor:#ffffff}
*5*



|
{set:cellbgcolor:#d3d3d3}
*6*



|
{set:cellbgcolor:#d3d3d3}
*7*



|
{set:cellbgcolor:#ffffff}
*8*



|
{set:cellbgcolor:#ffffff}
*9*



|
{set:cellbgcolor:#ffffff}
*10*



|
{set:cellbgcolor:#ffffff}
*11*



|
{set:cellbgcolor:#ffffff}
*12*



|
{set:cellbgcolor:#d3d3d3}
*13*



|
{set:cellbgcolor:#d3d3d3}
*14*



|
{set:cellbgcolor:#ffffff}
*15*



|
{set:cellbgcolor:#ffffff}
*16*

Sprint 7 (Ende)



|
{set:cellbgcolor:#ffffff}
*17*

Sprint 8 (Start)



|
{set:cellbgcolor:#ffffff}
*18*



|
{set:cellbgcolor:#ffffff}
*19*



|
{set:cellbgcolor:#d3d3d3}
*20*



|
{set:cellbgcolor:#d3d3d3}
*21*



|
{set:cellbgcolor:#ffffff}
*22*



|
{set:cellbgcolor:#ffffff}
*23*



|
{set:cellbgcolor:#ffffff}
*24*



|
{set:cellbgcolor:#ffffff}
*25*



|
{set:cellbgcolor:#ffffff}
*26*



|
{set:cellbgcolor:#d3d3d3}
*27*



|
{set:cellbgcolor:#d3d3d3}
*28*



|
{set:cellbgcolor:#ffffff}
*29*



|
{set:cellbgcolor:#ffffff}
*30*

Sprint 8 (Ende)



|
{set:cellbgcolor:#ffffff}
*31*

Sprint 9 (Start)


{set:cellbgcolor:none}	
||||

|===

==== 2016.9

[cols="3,3,3,3,3"]
|===

|
{set:cellbgcolor:#ffffff}
*1*



|
{set:cellbgcolor:#ffffff}
*2*



|
{set:cellbgcolor:#d3d3d3}
*3*



|
{set:cellbgcolor:#d3d3d3}
*4*



|
{set:cellbgcolor:#ffffff}
*5*



|
{set:cellbgcolor:#ffffff}
*6*



|
{set:cellbgcolor:#ffffff}
*7*



|
{set:cellbgcolor:#ffffff}
*8*



|
{set:cellbgcolor:#ffffff}
*9*



|
{set:cellbgcolor:#d3d3d3}
*10*



|
{set:cellbgcolor:#d3d3d3}
*11*



|
{set:cellbgcolor:#ffffff}
*12*



|
{set:cellbgcolor:#ffffff}
*13*

Sprint 9 (Ende)



|
{set:cellbgcolor:#ffffff}
*14*

Sprint 10 (Start)



|
{set:cellbgcolor:#ffffff}
*15*



|
{set:cellbgcolor:#ffffff}
*16*



|
{set:cellbgcolor:#d3d3d3}
*17*



|
{set:cellbgcolor:#d3d3d3}
*18*



|
{set:cellbgcolor:#ffffff}
*19*



|
{set:cellbgcolor:#ffffff}
*20*



|
{set:cellbgcolor:#ffffff}
*21*



|
{set:cellbgcolor:#ffffff}
*22*



|
{set:cellbgcolor:#ffffff}
*23*



|
{set:cellbgcolor:#d3d3d3}
*24*



|
{set:cellbgcolor:#d3d3d3}
*25*



|
{set:cellbgcolor:#ffffff}
*26*



|
{set:cellbgcolor:#ffffff}
*27*

Sprint 10 (Ende)



|
{set:cellbgcolor:#ffffff}
*28*

Sprint 11 (Start)



|
{set:cellbgcolor:#ffffff}
*29*



|
{set:cellbgcolor:#ffffff}
*30*


{set:cellbgcolor:none}	
|||||

|===

==== 2016.10

[cols="3,3,3,3,3"]
|===

|
{set:cellbgcolor:#d3d3d3}
*1*



|
{set:cellbgcolor:#d3d3d3}
*2*



|
{set:cellbgcolor:#ffffff}
*3*



|
{set:cellbgcolor:#ffffff}
*4*



|
{set:cellbgcolor:#ffffff}
*5*



|
{set:cellbgcolor:#ffffff}
*6*



|
{set:cellbgcolor:#ffffff}
*7*



|
{set:cellbgcolor:#d3d3d3}
*8*



|
{set:cellbgcolor:#d3d3d3}
*9*



|
{set:cellbgcolor:#ffffff}
*10*



|
{set:cellbgcolor:#ffffff}
*11*

Sprint 11 (Ende)



|
{set:cellbgcolor:#ffffff}
*12*

Sprint 12 (Start)



|
{set:cellbgcolor:#ffffff}
*13*



|
{set:cellbgcolor:#ffffff}
*14*



|
{set:cellbgcolor:#d3d3d3}
*15*



|
{set:cellbgcolor:#d3d3d3}
*16*



|
{set:cellbgcolor:#ffffff}
*17*



|
{set:cellbgcolor:#ffffff}
*18*



|
{set:cellbgcolor:#ffffff}
*19*



|
{set:cellbgcolor:#ffffff}
*20*



|
{set:cellbgcolor:#ffffff}
*21*



|
{set:cellbgcolor:#d3d3d3}
*22*



|
{set:cellbgcolor:#d3d3d3}
*23*



|
{set:cellbgcolor:#ffffff}
*24*



|
{set:cellbgcolor:#ffffff}
*25*

Meilensteine (Ende)

Sprint 12 (Ende)



|
{set:cellbgcolor:#ffffff}
*26*

Sprint 13 (Start)



|
{set:cellbgcolor:#ffffff}
*27*



|
{set:cellbgcolor:#ffffff}
*28*



|
{set:cellbgcolor:#d3d3d3}
*29*



|
{set:cellbgcolor:#d3d3d3}
*30*



|
{set:cellbgcolor:#ffffff}
*31*


{set:cellbgcolor:none}	
||||

|===


=== Meilensteine



Berechnete Velocity (alle Sprints): 0.0

==== Konzeptphase




===== Release MS20



[cols="10,20"]
|===
|*Startdatum*|2016-01-21_Thu
|*Enddatum*|2016-12-06_Tue
|===


===== Release MS21



[cols="10,20"]
|===
|*Startdatum*|2016-01-21_Thu
|*Enddatum*|2016-12-06_Tue
|===




=== Sprints




==== Sprint 1



[cols="10,20"]
|===
|*Startdatum*|2016-01-21_Thu
|*Enddatum*|2016-02-03_Wed
|===
===== Sprint 1 Ziele



[cols="2,10a" options="header"]
|===
|Name|Beschreibung
|ssss  
| 
dfsdf

|dsfsdfsdf  
| 
asdfasdf

|asdf  
| 
asdfasdf

|===


===== Sprint 1 Kapazität



.Zusammenfassung
[cols="10,20"]
|===
|*Butto Kapazität [h]*|80
|*Netto Kapazität [h]*|64
|*Aufwand [PT]*|0.0
|*Leistung (Aufwand/Netto Kapazität)*|0.0
|===

[cols="10,10,10,10" options="header"]
|===
|Person|Brutto Kapazität [h]|Produktivität|Netto Kapazität [h]
|Pascal Meier
|80
|80%
|64
|===

.Kapazität 
[cols="4,^4" options="header"]
|===
|Date
|Pascal Meier
|
{set:cellbgcolor:none}
2016-01-21_Thu
^|
{set:cellbgcolor:#009933}
8
|
{set:cellbgcolor:none}
2016-01-22_Fri
^|
{set:cellbgcolor:#009933}
8
|
{set:cellbgcolor:none}
2016-01-23_Sat
^|
{set:cellbgcolor:#d3d3d3}
0
|
{set:cellbgcolor:none}
2016-01-24_Sun
^|
{set:cellbgcolor:#d3d3d3}
0
|
{set:cellbgcolor:none}
2016-01-25_Mon
^|
{set:cellbgcolor:#009933}
8
|
{set:cellbgcolor:none}
2016-01-26_Tue
^|
{set:cellbgcolor:#009933}
8
|
{set:cellbgcolor:none}
2016-01-27_Wed
^|
{set:cellbgcolor:#009933}
8
|
{set:cellbgcolor:none}
2016-01-28_Thu
^|
{set:cellbgcolor:#009933}
8
|
{set:cellbgcolor:none}
2016-01-29_Fri
^|
{set:cellbgcolor:#009933}
8
|
{set:cellbgcolor:none}
2016-01-30_Sat
^|
{set:cellbgcolor:#d3d3d3}
0
|
{set:cellbgcolor:none}
2016-01-31_Sun
^|
{set:cellbgcolor:#d3d3d3}
0
|
{set:cellbgcolor:none}
2016-02-01_Mon
^|
{set:cellbgcolor:#009933}
8
|
{set:cellbgcolor:none}
2016-02-02_Tue
^|
{set:cellbgcolor:#009933}
8
|
{set:cellbgcolor:none}
2016-02-03_Wed
^|
{set:cellbgcolor:#009933}
8

|===
{set:cellbgcolor:none}


===== Sprint 1 SprintBacklog 



[cols="10,20a,^5,^5,5,^5" options="header"]
|===
|Name|Beschreibung|State|Verantwortlich(e)|Lieferergbnis|Aufwand [PT]
|===



==== Sprint 2



[cols="10,20"]
|===
|*Startdatum*|2016-01-02_Sat
|*Enddatum*|2016-01-02_Sat
|===
===== Sprint 2 Ziele



[cols="2,10a" options="header"]
|===
|Name|Beschreibung
|===


===== Sprint 2 Kapazität



.Zusammenfassung
[cols="10,20"]
|===
|*Butto Kapazität [h]*|0
|*Netto Kapazität [h]*|0
|*Aufwand [PT]*|0.0
|*Leistung (Aufwand/Netto Kapazität)*|NaN
|===

[cols="10,10,10,10" options="header"]
|===
|Person|Brutto Kapazität [h]|Produktivität|Netto Kapazität [h]
|===

.Kapazität 
[cols="4," options="header"]
|===
|Date

|===
{set:cellbgcolor:none}


===== Sprint 2 SprintBacklog 



[cols="10,20a,^5,^5,5,^5" options="header"]
|===
|Name|Beschreibung|State|Verantwortlich(e)|Lieferergbnis|Aufwand [PT]
|===



==== Sprint 3



[cols="10,20"]
|===
|*Startdatum*|2016-05-27_Fri
|*Enddatum*|2016-06-21_Tue
|===


==== Sprint 4



[cols="10,20"]
|===
|*Startdatum*|2016-06-22_Wed
|*Enddatum*|2016-07-05_Tue
|===


==== Sprint 5



[cols="10,20"]
|===
|*Startdatum*|2016-07-06_Wed
|*Enddatum*|2016-07-19_Tue
|===


==== Sprint 6



[cols="10,20"]
|===
|*Startdatum*|2016-07-20_Wed
|*Enddatum*|2016-08-02_Tue
|===


==== Sprint 7



[cols="10,20"]
|===
|*Startdatum*|2016-08-03_Wed
|*Enddatum*|2016-08-16_Tue
|===


==== Sprint 8



[cols="10,20"]
|===
|*Startdatum*|2016-08-17_Wed
|*Enddatum*|2016-08-30_Tue
|===


==== Sprint 9



[cols="10,20"]
|===
|*Startdatum*|2016-08-31_Wed
|*Enddatum*|2016-09-13_Tue
|===


==== Sprint 10



[cols="10,20"]
|===
|*Startdatum*|2016-09-14_Wed
|*Enddatum*|2016-09-27_Tue
|===


==== Sprint 11



[cols="10,20"]
|===
|*Startdatum*|2016-09-28_Wed
|*Enddatum*|2016-10-11_Tue
|===


==== Sprint 12



[cols="10,20"]
|===
|*Startdatum*|2016-10-12_Wed
|*Enddatum*|2016-10-25_Tue
|===


==== Sprint 13



[cols="10,20"]
|===
|*Startdatum*|2016-10-26_Wed
|*Enddatum*|2016-11-08_Tue
|===


==== Sprint 14



[cols="10,20"]
|===
|*Startdatum*|2016-11-09_Wed
|*Enddatum*|2016-11-22_Tue
|===


==== Sprint 15



[cols="10,20"]
|===
|*Startdatum*|2016-11-23_Wed
|*Enddatum*|2016-12-06_Tue
|===



=== Termine



.Alle offenen Termine
[cols="5,10a,7a,7a,5" options="header"]
|===
|Datum|Name|Verantwortlicher|Teilnehmer|Lieferergebnis
|2016-01-01_Fri | Sprint Retospektive 2 | Pascal Meier 
| 
Pascal Meier

|
|2016-01-02_Sat | Workshop | Pascal Meier 
| 
Pascal Meier

|
|===

.Alle erledigten Termine
[cols="5,10a,7a,7a,5" options="header"]
|===
|Datum|Name|Verantwortlicher|Teilnehmer|Lieferergebnis
|2016-01-01_Fri | Sprint Review 2 | Pascal Meier 
| 
Pascal Meier

|
|===




