// Begin Protected Region [[meta-data]]

// End Protected Region   [[meta-data]]

:toc:

[#chapter-system_scope_and_context]
== System Scope and Context
In this chapter, the context of the considered system (Chess) is outlined.
// Begin Protected Region [[bfc8585e-2661-11e6-ae54-e50d44645ae7,customText]]

// End Protected Region   [[bfc8585e-2661-11e6-ae54-e50d44645ae7,customText]]

[#chapter-domain_context]
=== Domain Context
[plantuml, png]
....
skinparam monochrome true
skinparam componentStyle uml2
actor Player__F_A as "Player A"
actor Player__F_B as "Player B"
component Chess as "Chess" <<SoftwareSystem>>
Chess -up-> Player__F_A : gets
Player__F_A -down-> Chess : interacts
Player__F_B -down-> Chess : interacts
...
The following table describes the actuators of the considered system.
[cols="40%,60%"]
|===
|Actor | Description
|Player A
|
|Player B
|
|===

The following table describes the communication flows (Flows) between all participants and the system.
[cols="15%,15%,20%,50%"]
|===
|From | To | Interaction | Description
|Chess
|Player A</db:para>
|gets</db:para>
|
|Player A
|Chess</db:para>
|interacts</db:para>
|
|Player B
|Chess</db:para>
|interacts</db:para>
|
|===
// Begin Protected Region [[cb488719-2661-11e6-ae54-e50d44645ae7,customText]]

// End Protected Region   [[cb488719-2661-11e6-ae54-e50d44645ae7,customText]]

[#chapter-technical_context]
=== Technical Context
[plantuml, png]
....
skinparam monochrome true
skinparam componentStyle uml2
component FTP as "FTP" <<ExternalSystem>>
component Chess as "Chess" <<SoftwareSystem>>
FTP --> Chess : "verwendet"
Chess --> FTP : "verwendet"
...
The following table describes the neighboring systems of the considered system.
[cols="40%,60%"]
|===
|Neighboring System | Description
|FTP</db:para>
|
dsfasdf</db:para>
// Begin Protected Region [[d6de1d03-27f5-11e6-b263-9db62e053e59,customText]]

// End Protected Region   [[d6de1d03-27f5-11e6-b263-9db62e053e59,customText]]

// Actifsource ID=[803ac313-d64b-11ee-8014-c150876d6b6e,bfc8585e-2661-11e6-ae54-e50d44645ae7,dd79cee8-3339-11e8-a9fe-87ba35d8f5c4,bfc8585e-2661-11e6-ae54-e50d44645ae7,6+1a4z9+Rqv8gUs7lVdXJVC8eFo=]
