name: Package Eclipse for Windows, Linux and MacOS with x86_64 and arm64

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        arch: [x86_64, arm64]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python (or other environment if needed)
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'  # Adapt depending on the environment

      # Set up build tools based on the platform
      - name: Init Build
        run: |
          $GITHUB_WORKSPACE/build/init.sh
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
              
          elif [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            
          elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            
          fi

      - name: Build for ${{ matrix.arch }} architecture
        run: |
          invoke package-eclipse