name: Package Eclipse for Windows, Linux and MacOS

on:
  push:
    branches: ["master"]
    paths:
      - 'build/**'  # Triggers the workflow only if changes are made in the build directory
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    strategy:
      max-parallel: 1  # This line ensures sequential execution
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]  # Defined specific images
    runs-on: ${{ matrix.os }}

    steps:
      - name: Enable Git long paths
        run: git config --global core.longpaths true
      
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python (or other environment if needed)
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Build for Windows
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          cd "${{ github.workspace }}/build"
          ./init.cmd
          ./myenv/Scripts/invoke.exe install-eclipse-components --no-with-optional package-eclipse

      - name: Build for Linux/MacOS
        if: ${{ matrix.os != 'windows-latest' }}
        run: |
          cd "${{ github.workspace }}/build"
          ./init.sh
          ./myenv/bin/invoke install-eclipse-components --no-with-optional package-eclipse
